Handle zero availability case
ymcatwincities/openy_activity_finder pull request #149
Opened 2022-02-17 21:44 UTC by froboy

2022-02-17 22:45 UTC, froboy commented on src/OpenyActivityFinderSolrBackend.php
> -        'spots_available' => !$entity->field_availability->isEmpty() ? $entity->field_availability->value : '',
Drupal's `isEmpty` just wraps PHP's, which considers `0` as empty.

2022-02-17 22:46 UTC, froboy commented on templates/openy-activity-finder-program-search-page.html.twig
> +                        <div v-if="item.spots_available" v-bind:class="[item.spots_available <= 3 ? item.spots_available == 1 ? 'few-spots only-one' : 'few-spots' : '', 'spots-availability']">${ item
```suggestion
                        <div v-if="item.spots_available >=1" v-bind:class="[item.spots_available <= 3 ? item.spots_available == 1 ? 'few-spots only-one' : 'few-spots' : '', 'spots-availability']">
                          ${ item.spots_available }
```

2022-02-17 22:47 UTC, froboy commented on templates/openy-activity-finder-program-search-page.html.twig
> +                          left</div>
```suggestion
                          left
                        </div>
```

2022-02-19 09:37 UTC, duozersk requested changes
Drupal API is checking for NULL

2022-02-19 09:37 UTC, duozersk commented on src/OpenyActivityFinderSolrBackend.php
> -        'spots_available' => !$entity->field_availability->isEmpty() ? $entity->field_availability->value : '',
No, Drupal's `isEmpty()` specifically checks for NULL - https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21TypedData%21Plugin%21DataType%21ItemList.php/function/ItemList%3A%3AisEmpty/9.3.x

This change might conflict with Activity Finder 4 implementation... I did a deep dive on it about a year ago: https://github.com/ymcatwincities/openy_activity_finder/commit/abe64f98aa3fa9a0ef04a7926ac6f546996b4b15 and https://github.com/ymcatwincities/openy_activity_finder/commit/c2495cbe334f0355a9f454d47b5e03ea02c36ccb

Null coalescence on the value is probably doing the same thing, meaning that this code change shouldn't actually change a thing. I still tend to have Drupal API `isEmpty()` here.

Activity Finder 4 already uses the 0 value of available spots: https://github.com/ymcatwincities/openy_activity_finder/blob/4.x/openy_af4_vue_app/src/components/modals/ActivityDetails.vue#L254 - see `getButtonTitle()` and `isRegisterDisabled()`; and here https://github.com/ymcatwincities/openy_activity_finder/blob/4.x/openy_af4_vue_app/src/components/AvailableSpots.vue#L26

And you can see it working on the sandbox here: https://sandbox-carnation-cus-d9.openy.org/activity-finder-v4?step=results

![image](https://user-images.githubusercontent.com/2128648/154795396-37a562c4-9aef-4640-915b-53ce34a9a555.png)
![image](https://user-images.githubusercontent.com/2128648/154795439-883c6c92-60e9-4a24-b117-e8fe9ffd1c75.png)

2022-02-21 20:32 UTC, froboy commented on src/OpenyActivityFinderSolrBackend.php
> -        'spots_available' => !$entity->field_availability->isEmpty() ? $entity->field_availability->value : '',
@duozersk thanks for your clarification. I think I had two issues:

1. My project was on an older version and didn't have your new logic using Drupal's `isEmpty`, it was still using PHP's `empty`. I believe you're correct and my edit here is not necessary.
2. My project it still using AF3, which uses the twig templates below. I think that change is still necessary, but won't be reflected in the sandbox as they're using AF4.

2022-02-21 20:32 UTC, froboy commented on src/OpenyActivityFinderSolrBackend.php
> +        'spots_available' => $entity->field_availability->value ?? '',
```suggestion
        'spots_available' => !$entity->field_availability->isEmpty() ? $entity->field_availability->value : '',
```

2022-03-09 15:28 UTC, podarok commented
Is it ready ? @froboy

2022-03-09 15:34 UTC, froboy commented
@podarok yes, I believe so.

2022-03-10 10:54 UTC, merged