MAINTAIN-191 Daxko limit by category
ymcatwincities/openy_activity_finder pull request #181
Opened 2022-05-20 21:00 UTC by froboy

Resolves https://openy.atlassian.net/browse/MAINTAIN-191

Daxko limit field is being saved in a different field as it's just a string instead of an entity-reference. The app logic (shockingly) took care of everything once the category id was passed in, so yay!

To test:
- configure Daxko Activity Finder settings at /admin/config/services/daxko2
- set AF to use the Daxko backend at /admin/openy/settings/activity-finder
- add/edit an AF4 block, add a category or more (by id) 
![Edit_Landing_Page_Activity_Finder_v4_-_Limit_to_camps___Drush_Site-Install](https://user-images.githubusercontent.com/238201/169609649-bf681916-a85c-4a2e-9c66-bebf5dff205f.png)
- save and test, only the listed categories should be available in the activity step
![Activity_Finder_v4_-_Limit_to_camps___Drush_Site-Install](https://user-images.githubusercontent.com/238201/169609816-d050ee0c-1a77-4f5b-9a96-8caf5a4aac55.png)
- only the selected categories should be available in the filters and results.
![Activity_Finder_v4_-_Limit_to_camps___Drush_Site-Install](https://user-images.githubusercontent.com/238201/169609923-3b1607f0-2465-42f4-ade4-0414ec5a1f21.png)

2022-05-23 15:02 UTC, podarok requested changes
Small changes, please @froboy

2022-05-23 15:02 UTC, podarok commented on src/Plugin/Block/ActivityFinder4Block.php
> +      $limit_by_category = $conf['limit_by_category'];
Use define early pattern https://www.drupal.org/node/3281070
Less code, no spaghetti @froboy

2022-05-23 15:02 UTC, podarok commented on src/Plugin/Block/ActivityFinder4Block.php
> +  public function getBackend(): array
let's add in composer.json minimum PHP version constraint for this code style

2022-05-27 14:18 UTC, froboy commented on src/Plugin/Block/ActivityFinder4Block.php
> +  public function getBackend(): array
@podarok from what I can tell this is supported way back in php 7.1? Is there something I'm missing? It's new to me (thanks to PHPStorm) but seems like not new to PHP?

2022-05-27 14:30 UTC, podarok commented on src/Plugin/Block/ActivityFinder4Block.php
> +  public function getBackend(): array
No, all good. 
I'm still getting used to this style of "new" PHP. But seems l'm older than this style - is an issue )))

2022-05-27 14:31 UTC, merged

2022-05-27 14:42 UTC, froboy commented on src/Plugin/Block/ActivityFinder4Block.php
> +  public function getBackend(): array
What's what happens when we let computers help us code. TIL too.