[MAINTAIN-177] - Clear searched keywords by Clear filters button
ymcatwincities/openy_activity_finder pull request #96
Opened 2021-10-08 08:25 UTC by manachynskyi

This pr is going to add new `Clear keywords` button.

Steps for review:
- [ ] Visit activity finder 4 page
- [ ] go through all steps to the result page and perform a search by some keyword that won't return results (e.g. test) 
- [x] make sure there is a `Clear keyword` button present https://i.imgur.com/bbTDT8J.png (it should clear keywords)
- [ ] type keyword again (without results) and additionally select some filter
- [x] `Clear filters` buttons should appear. https://i.imgur.com/WBE4G9L.png
- [ ] Additionally, select several of any other filters
- [x] make sure you see buttons, each of them should leave **ONLY** a selected filter specified in the button title, while keywords shouldn't be cleared https://i.imgur.com/q2VAMFF.png

2021-10-08 09:07 UTC, hamrant approved these changes

2021-10-11 07:45 UTC, duozersk requested changes
I don't have access to the https://openy.atlassian.net/browse/MAINTAIN-177... the access was requested (Julia Z have asked Sarah B to provide access for me)
The "Clear filters" functionality was specifically designed to not clear the keywords filter - so we need to check with initial stakeholders if this is fine to change it globally (for all the "Clear filters" appearances in the application).

2021-10-12 11:49 UTC, podarok commented
@sarah-halby we should check with Ben/Craig if keywords search should be cleared when using "Clear filters" button
I second @duozersk - I remember we initially disabled clearing keywords. https://openy.atlassian.net/browse/MAINTAIN-177?focusedCommentId=12607

2021-10-12 14:25 UTC, podarok commented
As a suggestion - we should make this feature optional and disabled by default. When someone needs it enabled - should be a checkbox on the Paragraph configuration level
@manachynskyi @duozersk

2021-10-21 15:40 UTC, podarok approved these changes
Code wise looks good

2021-10-22 08:25 UTC, duozersk requested changes

2021-10-22 08:25 UTC, duozersk commented on openy_af4_vue_app/src/App.vue
> +      this['searchKeywords'] = ''
Strange notation... why not `this.searchKeywords` like in all the other places?

2021-10-22 08:25 UTC, duozersk commented on openy_af4_vue_app/src/components/NoResults.vue
> +      }
No, it is definitely a change to the logic we had before. We need to clear keywords only when the user explicitly wants to clear them.
And even if we need to clear them - this action should not be in this component, this logic should be in the App.vue component level, not here.

I would just remove this piece for now.

2021-10-22 12:31 UTC, manachynskyi commented on openy_af4_vue_app/src/components/NoResults.vue
> +      }
@duozersk This piece will be invoked only when criteria are displayed [image](https://i.imgur.com/TaFF7gP.png ). If we remove this piece, the logic will little bit strange, the user chose the most important criteria, but not all filters will be cleared.

The logic of clearing located in App.vue, in this pieace we just emit event.

2021-10-22 12:47 UTC, podarok commented
this is approved by Ben, we can move forward with merging
Let me know when this is ready for final review @duozersk @manachynskyi

2021-10-22 18:43 UTC, duozersk commented on openy_af4_vue_app/src/components/NoResults.vue
> +      }
@manachynskyi ok, let's have a call then; I'll find you ;)

2021-10-25 11:37 UTC, manachynskyi commented on openy_af4_vue_app/src/App.vue
> +      this['searchKeywords'] = ''
Fixed.

2021-10-25 11:38 UTC, manachynskyi commented on openy_af4_vue_app/src/components/NoResults.vue
> +      }
Fixed.

2021-10-25 12:10 UTC, duozersk approved these changes

2021-10-25 12:18 UTC, podarok approved these changes
Code looks good
Merging for dev testing by QA on sandboxes

2021-10-25 12:19 UTC, merged